version: 0.2

env:
  variables:
    NODE_ENV: "production"
    
phases:
  install:
    commands:
      - echo Installing dependency...
      - npm install -g next
      - npm install -g typescript
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
artifacts:
  files:
  secondary-artifacts:
    artifact1:
      files:
        - out/_next/**/*
      discard-paths: no
    artifact2:
      files:
        - out/index.html
        - out/users.html
        - out/404.html
      discard-paths: yes